# Sidebar Avatar
avatar:
  # Replace the default image and set the url here.
  url: #/images/avatar.gif

favicon:
  small: #/images/favicon-16x16.png
  medium: #/images/favicon-32x32.png
  apple_touch_icon: #/images/apple-touch-icon.png
  safari_pinned_tab: #/images/logo.svg

# Browser header panel color.
theme_color:
  light: "#F3F3F3"
  dark: "#202020"

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

footer:
  # Specify the year when the site was setup. If not defined, current year will be used.
  #since: 2021
  #github: https://github.com/yourname

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/about/cclicenses/
creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: small
  sidebar: false
  post: false
  # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
  # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
  language:

# Table of Contents in the Sidebar
# Front-matter variable (nonsupport wrap expand_all).
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false
  # Maximum heading depth of generated toc.
  max_depth: 6

# Code Highlight theme
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark

# TagCloud settings for tags page.
tagcloud:
  min: 12 # Minimum font size in px
  max: 30 # Maximum font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order

# Local Search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: true

giscus:
  enable: false
  repo: # yourname/yourrepo
  category: # target_category
  mapping: og:title # pathname | url | title | og:title
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom

# Google Webmaster tools verification.
# See: https://developers.google.com/search
google_site_verification:

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmasters
bing_site_verification:

# Yandex Webmaster tools verification.
# See: https://webmaster.yandex.ru
yandex_site_verification:

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Google Analytics
# See: https://analytics.google.com
google_analytics:
  tracking_id: # <app_id>
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false
  # only needed if you are using `only_pageview` mode, https://developers.google.com/analytics/devguides/collection/protocol/ga4
  measure_protocol_api_secret:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# Growingio Analytics
# See: https://www.growingio.com
growingio_analytics: # <project_id>

# Cloudflare Web Analytics
# See: https://www.cloudflare.com/web-analytics/
cloudflare_analytics:

# Microsoft Clarity Analytics
# See: https://clarity.microsoft.com/
clarity_analytics: # <project_id>

# Matomo Analytics
# See: https://matomo.org/
matomo:
  enable: false
  server_url: # https://www.example.com/
  site_id: # <your site id>

# Umami Analytics
# See: https://umami.is/
umami:
  enable: false
  script_url: # https://umami.example.com/script.js
  website_id: # <your website id>
  host_url: # <your umami site url>

# Plausible Analytics
# See: https://plausible.io/
plausible:
  enable: false
  script_url: # https://plausible.io/js/script.js
  site_domain: # www.example.com

webmanifest:
  enable: false

service_worker:
  enable: false

babel:
  options:
    sourceType: unambiguous

terser:
  js:
    mangle: true
    sourceMap: false
  html:
    collapseBooleanAttributes: true
    collapseWhitespace: true
    minifyCSS: true
    minifyJS: true
    removeComments: true
    removeEmptyAttributes: true
    removeScriptTypeAttributes: true
    removeStyleLinkTypeAttributes: true
    sortAttributes: true
    sortClassName: true

# Assets
css: css
js: js
images: images
